- name: Start AWS VM
  hosts: AWX
  gather_facts: false
#  connection: local
  environment:
    PATH: '{{ lookup(''env'', ''PATH'') }}:/home/{{ username }}/.local/bin/aws'
  tasks:
    - name: Start ec2 instances
#      amazon.aws.ec2:
#        instance_ids: '{{ instance_ids }}'
#        region: '{{ region }}'
#        state: running
#        wait: True
#        vpc_subnet_id: '{{ subnet_id }}'
      shell: chdir=/home/{{ username }}/.local/bin/ ./aws start-instance --instance-ids {{ instance_ids }}
