- name: Stop AWS VM
  hosts: AWX
  gather_facts: false
  environment:
    PATH: '{{ lookup(''env'', ''PATH'') }}:/usr/local/aws-cli/v2/2.6.1/bin/aws'
  tasks:
    - name: Stop ec2 instances
      shell: chdir=/usr/local/aws-cli/v2/2.6.1/bin/ ./aws ec2 stop-instances --instance-ids {{ instance_ids }}
