- name: Start AWS VM
  hosts: AWX
  gather_facts: false
  environment:
    PATH: '{{ lookup(''env'', ''PATH'') }}:/home/{{ username }}/.local/bin/aws'
  tasks:
    - name: Start ec2 instances
      shell: chdir=/home/{{ username }}/.local/bin/ ./aws ec2 stop-instances --instance-ids {{ instance_ids }}
