---
- name: Stop ec2 instances
  hosts: tag_Name_'{{ tag_name }}'
  gather_facts: false
  connection: local
  tasks:
    - name: Stop ec2 instances
      ec2:
        instance_ids: '{{ instance_ids }}'
        region: '{{ region }}'
        state: stopped
        wait: True
        vpc_subnet_id: '{{ subnet_id }}'
