---
- hosts: localhost
  gather_facts: true
  connection: local
  tasks:
    - name: Stop ec2 instances
#      amazon.aws.ec2:
#        instance_ids: '{{ instance_ids }}'
#        region: '{{ region }}'
#        state: stopped
#        wait: True
#        vpc_subnet_id: '{{ subnet_id }}'
      shell: aws stop-instance --instance-ids {{ instance_ids }}
